### ISSUE TITLE
Bad Performance due to BakeAllowedClasses frequently being called if using many sublevels

### ISSUE THREAD

**Issue by aspyralexni** [PipeRift/SaveExtension#55] opened 2020-08-05 21:58 UTC
**Describe the bug**
Because every USlotDataTask has a FSaveFilter, BakeAllowedClasses is called for each sub-level load, which can add up to bad performance if there are a number of sublevels.

**To Reproduce**
1. Create a map with a large number of sublevels (can be easier with world comp tool)
2. Move camera into area where numerous sublevels can load at once
3.  Notice bad performance due to BakeAllowedClasses being called once per sublevel load.

Suggest using only one FSaveFilter instance per game run.

Version 1.3

**Comment by muit** [comment] 2020-09-11 19:32
huh! this is an interesting problem!

The reason why levels save their own preset is that different levels could save different classes. FOr example you could decide to save the player only on the main level for performance.

Im surprised that baking classes is so slow. Worth a visit using the profiler.

Thanks for the report!

**Comment by muit** [comment] 2020-09-26 13:59
There was an issue that made filters build a lot more frequently and was likely the cause of the issue. It has been fixed now

**Closed** 2020-09-26 14:08 UTC
Labels: Bug, Reproduced

**Comment by muit** [comment] 2020-11-26 20:45
Appart from the previous fixes, now baking a class filter takes around 130 nanoseconds. Therefore any remaining performance problem has been solved.
