### ISSUE TITLE
Level BP variables don't get saved

### ISSUE THREAD

**Issue by fg16** [PipeRift/SaveExtension#5] opened 2018-12-21 10:10 UTC
**Describe the bug**

Global Variables placed in the 'level blueprint' don't save / load at all

**To Reproduce**

Save to ID with S 
Load from ID with L 
On the properties of variables check box 'SaveGame'

Variables are still not saving and every load generates a lot of console errors on the logs.

**Expected behavior**

Variables saving and loading properly

**Environment (please complete the following information):**

 - Engine Version: 4.21.1
 - Plugin Version: v1.0
 - OS: Windows 10 Insider v1709 and V1809 both tested

**Comment by muit** [comment] 2018-12-21 22:15
@fg16  could I ask you to attach that log? It would help a lot. Thanks!

**Comment by muit** [comment] 2018-12-27 21:14
Will see what possible fixes there are. For now, this bug is confirmed :)

**Comment by muit** [comment] 2019-01-07 17:00
Turns out, level scripts were being cleaned away when loading. Its now fixed

**Closed** 2019-01-07 17:02 UTC
Labels: Bug, Reproduced
